language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t simgesc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true simgesc/docker-react npm run test
 
